name: ERC success for 0.1/base

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Ninja
      run: |
        cmake -S tools/ninja -B tools/ninja/build
        make -j8 -C tools/ninja/build
    - name: Ensure erc success
      run: |
        ./tools/ninja/build/ninja build/0.1/base/erc_success
