name: Generate artifacts for 0.1/base

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  generate-ninja-file:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Generate ninja build file
      run: |
        python ./configure.py
    - uses: actions/upload-artifact@v2
      with:
        name: build.ninja
        path: build.ninja
  
  validate-ninja-file:
    needs:
      [generate-ninja-file]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/download-artifact@v2
      with:
        name: build.ninja
    - name: Fail if ninja build file is outdated
      run: |
        git diff --name-status | if [[ $(grep build.ninja) ]]; then exit 1; else exit 0; fi

  build-ninja:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Build Ninja
      run: |
        cmake -S tools/ninja -B tools/ninja/build
        make -j8 -C tools/ninja/build
    - uses: actions/upload-artifact@v2
      with:
        name: ninja
        path: ./tools/ninja/build/ninja

  run-erc-for-0-1-base:
    needs:
      [build-ninja, validate-ninja-file]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/download-artifact@v2
      with:
        name: ninja
    - name: Ensure erc success
      run: |
        chmod +x ninja
        ./ninja build/0.1/base/erc_success

  run-drc-for-0-1-base:
    needs:
      [build-ninja, validate-ninja-file]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/download-artifact@v2
      with:
        name: ninja
    - name: Ensure erc success
      run: |
        chmod +x ninja
        ./ninja build/0.1/base/drc_success
  
  generate-artifacts-for-0-1-base:
    needs:
      [run-erc-for-0-1-base, run-drc-for-0-1-base]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/download-artifact@v2
      with:
        name: ninja
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install kicad
      run: |
        sudo apt-get update && sudo apt-get install -y kicad
    - name: Install python dependencies
      run: |
        pip install numpy lxml mistune pybars3 wand pyyaml kicad-python pcbdraw
    - name: Generate artifacts
      run: |
        mkdir -p build/0.1/base
        touch build/0.1/base/erc_success
        touch build/0.1/base/drc_success
        chmod +x ninja
        ./ninja 0.1/base
