name: Validate ninja build file

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Update submodules
      run: |
        git submodules update --init --remote --recursive
    - name: Generate ninja build file
      run: |
        python ./configure.py
    - name: Fail if ninja build file is outdated
      run: |
        git diff --name-status | if [[ $(grep build.ninja) ]];then; return 1; else; return 0; fi
